# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Bitco\bitmessageqt\bitmessageui.ui'
#
# Created: Sat Jun 07 19:00:45 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(885, 580)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/treasure_chest.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(_fromUtf8(""))
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget_2 = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(30, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.sync_label = QtGui.QLabel(self.tab)
        self.sync_label.setGeometry(QtCore.QRect(170, 30, 121, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(247, 0, 4))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 0, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 1, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 0, 4))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 0, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 1, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.sync_label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.sync_label.setFont(font)
        self.sync_label.setAutoFillBackground(False)
        self.sync_label.setObjectName(_fromUtf8("sync_label"))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(50, 56, 64, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_balance = QtGui.QLabel(self.tab)
        self.label_balance.setGeometry(QtCore.QRect(130, 60, 91, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Adobe Heiti Std R"))
        font.setPointSize(10)
        self.label_balance.setFont(font)
        self.label_balance.setObjectName(_fromUtf8("label_balance"))
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(20, 90, 98, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_ucbalance = QtGui.QLabel(self.tab)
        self.label_ucbalance.setGeometry(QtCore.QRect(130, 90, 46, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Adobe Heiti Std R"))
        font.setPointSize(10)
        self.label_ucbalance.setFont(font)
        self.label_ucbalance.setObjectName(_fromUtf8("label_ucbalance"))
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(0, 150, 481, 101))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.lineEdit_10 = QtGui.QLineEdit(self.frame)
        self.lineEdit_10.setGeometry(QtCore.QRect(90, 10, 381, 20))
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.lineEdit_11 = QtGui.QLineEdit(self.frame)
        self.lineEdit_11.setGeometry(QtCore.QRect(90, 40, 381, 20))
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.label_45 = QtGui.QLabel(self.frame)
        self.label_45.setGeometry(QtCore.QRect(20, 9, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_45.setFont(font)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.label_46 = QtGui.QLabel(self.frame)
        self.label_46.setGeometry(QtCore.QRect(30, 40, 51, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_46.setFont(font)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.label_47 = QtGui.QLabel(self.frame)
        self.label_47.setGeometry(QtCore.QRect(10, 70, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_47.setFont(font)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.overviewamount = QtGui.QDoubleSpinBox(self.frame)
        self.overviewamount.setGeometry(QtCore.QRect(90, 70, 141, 22))
        self.overviewamount.setDecimals(10)
        self.overviewamount.setMaximum(21000000.0)
        self.overviewamount.setSingleStep(0.01)
        self.overviewamount.setProperty("value", 0.0)
        self.overviewamount.setObjectName(_fromUtf8("overviewamount"))
        self.sendbtc = QtGui.QPushButton(self.frame)
        self.sendbtc.setGeometry(QtCore.QRect(290, 70, 186, 22))
        self.sendbtc.setObjectName(_fromUtf8("sendbtc"))
        self.label_44 = QtGui.QLabel(self.tab)
        self.label_44.setGeometry(QtCore.QRect(110, 119, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_44.setFont(font)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.frame_2 = QtGui.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(0, 290, 881, 221))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.bitcoinaddresses = QtGui.QTableWidget(self.frame_2)
        self.bitcoinaddresses.setGeometry(QtCore.QRect(9, 9, 861, 211))
        self.bitcoinaddresses.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.EditKeyPressed)
        self.bitcoinaddresses.setAlternatingRowColors(True)
        self.bitcoinaddresses.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.bitcoinaddresses.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.bitcoinaddresses.setObjectName(_fromUtf8("bitcoinaddresses"))
        self.bitcoinaddresses.setColumnCount(3)
        self.bitcoinaddresses.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.bitcoinaddresses.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.bitcoinaddresses.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.bitcoinaddresses.setHorizontalHeaderItem(2, item)
        self.bitcoinaddresses.horizontalHeader().setCascadingSectionResizes(True)
        self.bitcoinaddresses.horizontalHeader().setDefaultSectionSize(360)
        self.bitcoinaddresses.horizontalHeader().setHighlightSections(False)
        self.bitcoinaddresses.horizontalHeader().setMinimumSectionSize(50)
        self.bitcoinaddresses.horizontalHeader().setSortIndicatorShown(False)
        self.bitcoinaddresses.horizontalHeader().setStretchLastSection(True)
        self.bitcoinaddresses.verticalHeader().setVisible(False)
        self.label_48 = QtGui.QLabel(self.tab)
        self.label_48.setGeometry(QtCore.QRect(240, 260, 181, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_48.setFont(font)
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.label_49 = QtGui.QLabel(self.tab)
        self.label_49.setGeometry(QtCore.QRect(625, 0, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_49.setFont(font)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.tableWidget = QtGui.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(480, 40, 391, 251))
        self.tableWidget.setProperty("showDropIndicator", True)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(124)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(33)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(36)
        self.tableWidget.verticalHeader().setMinimumSectionSize(19)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(190, 6, 371, 21))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setEnabled(True)
        self.label_11.setGeometry(QtCore.QRect(20, 245, 241, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(195, 3, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(194, 6, 9))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 0, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 4, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(195, 3, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(194, 6, 9))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 0, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 4, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 4, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.label_11.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setAcceptDrops(False)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.sync = QtGui.QProgressBar(self.tab)
        self.sync.setGeometry(QtCore.QRect(236, 63, 231, 21))
        self.sync.setProperty("value", 0)
        self.sync.setObjectName(_fromUtf8("sync"))
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(10, 270, 181, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.tabWidget_2.addTab(self.tab, _fromUtf8(""))
        self.tab6 = QtGui.QWidget()
        self.tab6.setObjectName(_fromUtf8("tab6"))
        self.tabWidget_3 = QtGui.QTabWidget(self.tab6)
        self.tabWidget_3.setGeometry(QtCore.QRect(10, 120, 861, 391))
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.buyer = QtGui.QWidget()
        self.buyer.setObjectName(_fromUtf8("buyer"))
        self.label_24 = QtGui.QLabel(self.buyer)
        self.label_24.setGeometry(QtCore.QRect(10, 50, 101, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.lineEdit_2 = QtGui.QLineEdit(self.buyer)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 50, 260, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Adobe Heiti Std R"))
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setText(_fromUtf8(""))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.pushButtonManualEscrowBuyer = QtGui.QPushButton(self.buyer)
        self.pushButtonManualEscrowBuyer.setGeometry(QtCore.QRect(540, 40, 81, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(24, 154, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(188, 211, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 236, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButtonManualEscrowBuyer.setPalette(palette)
        self.pushButtonManualEscrowBuyer.setObjectName(_fromUtf8("pushButtonManualEscrowBuyer"))
        self.label_28 = QtGui.QLabel(self.buyer)
        self.label_28.setGeometry(QtCore.QRect(240, 108, 251, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.textBrowser_2 = QtGui.QTextBrowser(self.buyer)
        self.textBrowser_2.setGeometry(QtCore.QRect(0, 130, 861, 241))
        self.textBrowser_2.setObjectName(_fromUtf8("textBrowser_2"))
        self.label_25 = QtGui.QLabel(self.buyer)
        self.label_25.setGeometry(QtCore.QRect(460, 80, 371, 21))
        self.label_25.setText(_fromUtf8(""))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.spinBox_2 = QtGui.QDoubleSpinBox(self.buyer)
        self.spinBox_2.setGeometry(QtCore.QRect(380, 50, 140, 22))
        self.spinBox_2.setDecimals(10)
        self.spinBox_2.setMaximum(999999.99)
        self.spinBox_2.setSingleStep(0.01)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.escrowlabelforbuyer = QtGui.QLineEdit(self.buyer)
        self.escrowlabelforbuyer.setGeometry(QtCore.QRect(100, 80, 260, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Adobe Heiti Std R"))
        self.escrowlabelforbuyer.setFont(font)
        self.escrowlabelforbuyer.setText(_fromUtf8(""))
        self.escrowlabelforbuyer.setObjectName(_fromUtf8("escrowlabelforbuyer"))
        self.frombox = QtGui.QComboBox(self.buyer)
        self.frombox.setGeometry(QtCore.QRect(100, 20, 260, 22))
        self.frombox.setObjectName(_fromUtf8("frombox"))
        self.frombox.addItem(_fromUtf8(""))
        self.pushButton_2 = QtGui.QPushButton(self.buyer)
        self.pushButton_2.setGeometry(QtCore.QRect(5, 20, 91, 22))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.comment = QtGui.QPlainTextEdit(self.buyer)
        self.comment.setGeometry(QtCore.QRect(650, 10, 171, 111))
        self.comment.setOverwriteMode(True)
        self.comment.setObjectName(_fromUtf8("comment"))
        self.tabWidget_3.addTab(self.buyer, _fromUtf8(""))
        self.merchant = QtGui.QWidget()
        self.merchant.setObjectName(_fromUtf8("merchant"))
        self.textBrowser_3 = QtGui.QTextBrowser(self.merchant)
        self.textBrowser_3.setGeometry(QtCore.QRect(0, 110, 861, 261))
        self.textBrowser_3.setObjectName(_fromUtf8("textBrowser_3"))
        self.label_40 = QtGui.QLabel(self.merchant)
        self.label_40.setGeometry(QtCore.QRect(0, 85, 301, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_40.setFont(font)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.label_26 = QtGui.QLabel(self.merchant)
        self.label_26.setGeometry(QtCore.QRect(450, 50, 341, 20))
        self.label_26.setText(_fromUtf8(""))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.newmerchantaddress = QtGui.QPushButton(self.merchant)
        self.newmerchantaddress.setGeometry(QtCore.QRect(74, 40, 211, 22))
        self.newmerchantaddress.setObjectName(_fromUtf8("newmerchantaddress"))
        self.youids = QtGui.QTableWidget(self.merchant)
        self.youids.setGeometry(QtCore.QRect(330, 2, 481, 101))
        self.youids.setStyleSheet(_fromUtf8(""))
        self.youids.setFrameShadow(QtGui.QFrame.Sunken)
        self.youids.setLineWidth(1)
        self.youids.setAlternatingRowColors(True)
        self.youids.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.youids.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.youids.setColumnCount(1)
        self.youids.setObjectName(_fromUtf8("youids"))
        self.youids.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.youids.setHorizontalHeaderItem(0, item)
        self.youids.horizontalHeader().setCascadingSectionResizes(True)
        self.youids.horizontalHeader().setDefaultSectionSize(0)
        self.youids.horizontalHeader().setMinimumSectionSize(52)
        self.youids.horizontalHeader().setSortIndicatorShown(True)
        self.youids.horizontalHeader().setStretchLastSection(True)
        self.youids.verticalHeader().setVisible(False)
        self.youids.verticalHeader().setDefaultSectionSize(26)
        self.youids.verticalHeader().setSortIndicatorShown(False)
        self.youids.verticalHeader().setStretchLastSection(False)
        self.tabWidget_3.addTab(self.merchant, _fromUtf8(""))
        self.label_20 = QtGui.QLabel(self.tab6)
        self.label_20.setGeometry(QtCore.QRect(20, 20, 841, 101))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setScaledContents(True)
        self.label_20.setWordWrap(True)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.tabWidget_2.addTab(self.tab6, _fromUtf8(""))
        self.tab7 = QtGui.QWidget()
        self.tab7.setObjectName(_fromUtf8("tab7"))
        self.textBrowser = QtGui.QTextBrowser(self.tab7)
        self.textBrowser.setGeometry(QtCore.QRect(250, 60, 621, 421))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.pushButton_3 = QtGui.QPushButton(self.tab7)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 13, 161, 31))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.offertype = QtGui.QComboBox(self.tab7)
        self.offertype.setGeometry(QtCore.QRect(20, 61, 201, 22))
        self.offertype.setObjectName(_fromUtf8("offertype"))
        self.offertype.addItem(_fromUtf8(""))
        self.offertype.addItem(_fromUtf8(""))
        self.offertype.addItem(_fromUtf8(""))
        self.comboBox_2 = QtGui.QComboBox(self.tab7)
        self.comboBox_2.setGeometry(QtCore.QRect(20, 102, 201, 22))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.lineEdit = QtGui.QLineEdit(self.tab7)
        self.lineEdit.setGeometry(QtCore.QRect(20, 184, 201, 20))
        self.lineEdit.setInputMask(_fromUtf8(""))
        self.lineEdit.setText(_fromUtf8(""))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label_12 = QtGui.QLabel(self.tab7)
        self.label_12.setGeometry(QtCore.QRect(20, 270, 211, 231))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(199, 0, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(199, 0, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_12.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.pushButton_4 = QtGui.QPushButton(self.tab7)
        self.pushButton_4.setGeometry(QtCore.QRect(60, 220, 111, 23))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.location = QtGui.QComboBox(self.tab7)
        self.location.setGeometry(QtCore.QRect(20, 142, 201, 22))
        self.location.setObjectName(_fromUtf8("location"))
        self.location.addItem(_fromUtf8(""))
        self.pushButton_5 = QtGui.QPushButton(self.tab7)
        self.pushButton_5.setGeometry(QtCore.QRect(300, 20, 81, 31))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.checkBox = QtGui.QCheckBox(self.tab7)
        self.checkBox.setGeometry(QtCore.QRect(420, 27, 301, 17))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.tabWidget_2.addTab(self.tab7, _fromUtf8(""))
        self.Advenced_messaging = QtGui.QWidget()
        self.Advenced_messaging.setObjectName(_fromUtf8("Advenced_messaging"))
        self.gridLayoutWidget = QtGui.QWidget(self.Advenced_messaging)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 881, 521))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.Advenced_messaging)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 885, 490))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setBaseSize(QtCore.QSize(0, 0))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.inbox = QtGui.QWidget()
        self.inbox.setObjectName(_fromUtf8("inbox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.inbox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayoutSearch = QtGui.QHBoxLayout()
        self.horizontalLayoutSearch.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayoutSearch.setObjectName(_fromUtf8("horizontalLayoutSearch"))
        self.inboxSearchLineEdit = QtGui.QLineEdit(self.inbox)
        self.inboxSearchLineEdit.setObjectName(_fromUtf8("inboxSearchLineEdit"))
        self.horizontalLayoutSearch.addWidget(self.inboxSearchLineEdit)
        self.inboxSearchOptionCB = QtGui.QComboBox(self.inbox)
        self.inboxSearchOptionCB.setObjectName(_fromUtf8("inboxSearchOptionCB"))
        self.inboxSearchOptionCB.addItem(_fromUtf8(""))
        self.inboxSearchOptionCB.addItem(_fromUtf8(""))
        self.inboxSearchOptionCB.addItem(_fromUtf8(""))
        self.inboxSearchOptionCB.addItem(_fromUtf8(""))
        self.inboxSearchOptionCB.addItem(_fromUtf8(""))
        self.horizontalLayoutSearch.addWidget(self.inboxSearchOptionCB)
        self.verticalLayout_2.addLayout(self.horizontalLayoutSearch)
        self.splitter = QtGui.QSplitter(self.inbox)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tableWidgetInbox = QtGui.QTableWidget(self.splitter)
        self.tableWidgetInbox.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidgetInbox.setAlternatingRowColors(True)
        self.tableWidgetInbox.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tableWidgetInbox.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidgetInbox.setWordWrap(False)
        self.tableWidgetInbox.setObjectName(_fromUtf8("tableWidgetInbox"))
        self.tableWidgetInbox.setColumnCount(4)
        self.tableWidgetInbox.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetInbox.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetInbox.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetInbox.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetInbox.setHorizontalHeaderItem(3, item)
        self.tableWidgetInbox.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetInbox.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidgetInbox.horizontalHeader().setHighlightSections(False)
        self.tableWidgetInbox.horizontalHeader().setMinimumSectionSize(27)
        self.tableWidgetInbox.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetInbox.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetInbox.verticalHeader().setVisible(False)
        self.tableWidgetInbox.verticalHeader().setDefaultSectionSize(26)
        self.textEditInboxMessage = QtGui.QTextEdit(self.splitter)
        self.textEditInboxMessage.setBaseSize(QtCore.QSize(0, 500))
        self.textEditInboxMessage.setReadOnly(True)
        self.textEditInboxMessage.setObjectName(_fromUtf8("textEditInboxMessage"))
        self.verticalLayout_2.addWidget(self.splitter)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/inbox.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.inbox, icon1, _fromUtf8(""))
        self.send = QtGui.QWidget()
        self.send.setObjectName(_fromUtf8("send"))
        self.gridLayout_3 = QtGui.QGridLayout(self.send)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pushButtonLoadFromAddressBook = QtGui.QPushButton(self.send)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButtonLoadFromAddressBook.setFont(font)
        self.pushButtonLoadFromAddressBook.setObjectName(_fromUtf8("pushButtonLoadFromAddressBook"))
        self.gridLayout_3.addWidget(self.pushButtonLoadFromAddressBook, 3, 2, 1, 1)
        self.pushButtonFetchNamecoinID = QtGui.QPushButton(self.send)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButtonFetchNamecoinID.setFont(font)
        self.pushButtonFetchNamecoinID.setObjectName(_fromUtf8("pushButtonFetchNamecoinID"))
        self.gridLayout_3.addWidget(self.pushButtonFetchNamecoinID, 3, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.send)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 5, 0, 1, 1)
        self.comboBoxSendFrom = QtGui.QComboBox(self.send)
        self.comboBoxSendFrom.setMinimumSize(QtCore.QSize(101, 0))
        self.comboBoxSendFrom.setObjectName(_fromUtf8("comboBoxSendFrom"))
        self.gridLayout_3.addWidget(self.comboBoxSendFrom, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.send)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 4, 0, 1, 1)
        self.labelFrom = QtGui.QLabel(self.send)
        self.labelFrom.setText(_fromUtf8(""))
        self.labelFrom.setObjectName(_fromUtf8("labelFrom"))
        self.gridLayout_3.addWidget(self.labelFrom, 2, 2, 1, 3)
        self.radioButtonSpecific = QtGui.QRadioButton(self.send)
        self.radioButtonSpecific.setChecked(True)
        self.radioButtonSpecific.setObjectName(_fromUtf8("radioButtonSpecific"))
        self.gridLayout_3.addWidget(self.radioButtonSpecific, 0, 1, 1, 1)
        self.lineEditTo = QtGui.QLineEdit(self.send)
        self.lineEditTo.setObjectName(_fromUtf8("lineEditTo"))
        self.gridLayout_3.addWidget(self.lineEditTo, 3, 1, 1, 1)
        self.textEditMessage = QtGui.QTextEdit(self.send)
        self.textEditMessage.setObjectName(_fromUtf8("textEditMessage"))
        self.gridLayout_3.addWidget(self.textEditMessage, 5, 1, 2, 5)
        self.label = QtGui.QLabel(self.send)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 3, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.send)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 297, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 6, 0, 1, 1)
        self.radioButtonBroadcast = QtGui.QRadioButton(self.send)
        self.radioButtonBroadcast.setObjectName(_fromUtf8("radioButtonBroadcast"))
        self.gridLayout_3.addWidget(self.radioButtonBroadcast, 1, 1, 1, 3)
        self.lineEditSubject = QtGui.QLineEdit(self.send)
        self.lineEditSubject.setText(_fromUtf8(""))
        self.lineEditSubject.setObjectName(_fromUtf8("lineEditSubject"))
        self.gridLayout_3.addWidget(self.lineEditSubject, 4, 1, 1, 5)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 3, 4, 1, 1)
        self.pushButtonSend = QtGui.QPushButton(self.send)
        self.pushButtonSend.setObjectName(_fromUtf8("pushButtonSend"))
        self.gridLayout_3.addWidget(self.pushButtonSend, 7, 5, 1, 1)
        self.labelSendBroadcastWarning = QtGui.QLabel(self.send)
        self.labelSendBroadcastWarning.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSendBroadcastWarning.sizePolicy().hasHeightForWidth())
        self.labelSendBroadcastWarning.setSizePolicy(sizePolicy)
        self.labelSendBroadcastWarning.setIndent(-1)
        self.labelSendBroadcastWarning.setObjectName(_fromUtf8("labelSendBroadcastWarning"))
        self.gridLayout_3.addWidget(self.labelSendBroadcastWarning, 7, 1, 1, 4)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/send.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.send, icon2, _fromUtf8(""))
        self.sent = QtGui.QWidget()
        self.sent.setObjectName(_fromUtf8("sent"))
        self.verticalLayout = QtGui.QVBoxLayout(self.sent)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.sentSearchLineEdit = QtGui.QLineEdit(self.sent)
        self.sentSearchLineEdit.setObjectName(_fromUtf8("sentSearchLineEdit"))
        self.horizontalLayout.addWidget(self.sentSearchLineEdit)
        self.sentSearchOptionCB = QtGui.QComboBox(self.sent)
        self.sentSearchOptionCB.setObjectName(_fromUtf8("sentSearchOptionCB"))
        self.sentSearchOptionCB.addItem(_fromUtf8(""))
        self.sentSearchOptionCB.addItem(_fromUtf8(""))
        self.sentSearchOptionCB.addItem(_fromUtf8(""))
        self.sentSearchOptionCB.addItem(_fromUtf8(""))
        self.sentSearchOptionCB.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.sentSearchOptionCB)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.splitter_2 = QtGui.QSplitter(self.sent)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.tableWidgetSent = QtGui.QTableWidget(self.splitter_2)
        self.tableWidgetSent.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidgetSent.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.tableWidgetSent.setAlternatingRowColors(True)
        self.tableWidgetSent.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tableWidgetSent.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidgetSent.setWordWrap(False)
        self.tableWidgetSent.setObjectName(_fromUtf8("tableWidgetSent"))
        self.tableWidgetSent.setColumnCount(4)
        self.tableWidgetSent.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetSent.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetSent.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetSent.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetSent.setHorizontalHeaderItem(3, item)
        self.tableWidgetSent.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetSent.horizontalHeader().setDefaultSectionSize(130)
        self.tableWidgetSent.horizontalHeader().setHighlightSections(False)
        self.tableWidgetSent.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetSent.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetSent.verticalHeader().setVisible(False)
        self.tableWidgetSent.verticalHeader().setStretchLastSection(False)
        self.textEditSentMessage = QtGui.QTextEdit(self.splitter_2)
        self.textEditSentMessage.setReadOnly(True)
        self.textEditSentMessage.setObjectName(_fromUtf8("textEditSentMessage"))
        self.verticalLayout.addWidget(self.splitter_2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/sent.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.sent, icon3, _fromUtf8(""))
        self.youridentities = QtGui.QWidget()
        self.youridentities.setObjectName(_fromUtf8("youridentities"))
        self.gridLayout_4 = QtGui.QGridLayout(self.youridentities)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.pushButtonNewAddress = QtGui.QPushButton(self.youridentities)
        self.pushButtonNewAddress.setObjectName(_fromUtf8("pushButtonNewAddress"))
        self.gridLayout_4.addWidget(self.pushButtonNewAddress, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(689, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 0, 1, 1, 1)
        self.tableWidgetYourIdentities = QtGui.QTableWidget(self.youridentities)
        self.tableWidgetYourIdentities.setFrameShadow(QtGui.QFrame.Sunken)
        self.tableWidgetYourIdentities.setLineWidth(1)
        self.tableWidgetYourIdentities.setAlternatingRowColors(True)
        self.tableWidgetYourIdentities.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidgetYourIdentities.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidgetYourIdentities.setObjectName(_fromUtf8("tableWidgetYourIdentities"))
        self.tableWidgetYourIdentities.setColumnCount(3)
        self.tableWidgetYourIdentities.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setKerning(True)
        item.setFont(font)
        self.tableWidgetYourIdentities.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetYourIdentities.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetYourIdentities.setHorizontalHeaderItem(2, item)
        self.tableWidgetYourIdentities.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetYourIdentities.horizontalHeader().setDefaultSectionSize(346)
        self.tableWidgetYourIdentities.horizontalHeader().setMinimumSectionSize(52)
        self.tableWidgetYourIdentities.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidgetYourIdentities.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetYourIdentities.verticalHeader().setVisible(False)
        self.tableWidgetYourIdentities.verticalHeader().setDefaultSectionSize(26)
        self.tableWidgetYourIdentities.verticalHeader().setSortIndicatorShown(False)
        self.tableWidgetYourIdentities.verticalHeader().setStretchLastSection(False)
        self.gridLayout_4.addWidget(self.tableWidgetYourIdentities, 1, 0, 1, 2)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/identities.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.youridentities, icon4, _fromUtf8(""))
        self.subscriptions = QtGui.QWidget()
        self.subscriptions.setObjectName(_fromUtf8("subscriptions"))
        self.gridLayout_5 = QtGui.QGridLayout(self.subscriptions)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_5 = QtGui.QLabel(self.subscriptions)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 2)
        self.pushButtonAddSubscription = QtGui.QPushButton(self.subscriptions)
        self.pushButtonAddSubscription.setObjectName(_fromUtf8("pushButtonAddSubscription"))
        self.gridLayout_5.addWidget(self.pushButtonAddSubscription, 1, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(689, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 1, 1, 1, 1)
        self.tableWidgetSubscriptions = QtGui.QTableWidget(self.subscriptions)
        self.tableWidgetSubscriptions.setAlternatingRowColors(True)
        self.tableWidgetSubscriptions.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidgetSubscriptions.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidgetSubscriptions.setObjectName(_fromUtf8("tableWidgetSubscriptions"))
        self.tableWidgetSubscriptions.setColumnCount(2)
        self.tableWidgetSubscriptions.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetSubscriptions.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetSubscriptions.setHorizontalHeaderItem(1, item)
        self.tableWidgetSubscriptions.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetSubscriptions.horizontalHeader().setDefaultSectionSize(400)
        self.tableWidgetSubscriptions.horizontalHeader().setHighlightSections(False)
        self.tableWidgetSubscriptions.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetSubscriptions.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetSubscriptions.verticalHeader().setVisible(False)
        self.gridLayout_5.addWidget(self.tableWidgetSubscriptions, 2, 0, 1, 2)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/subscriptions.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.subscriptions, icon5, _fromUtf8(""))
        self.addressbook = QtGui.QWidget()
        self.addressbook.setObjectName(_fromUtf8("addressbook"))
        self.gridLayout_6 = QtGui.QGridLayout(self.addressbook)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_6 = QtGui.QLabel(self.addressbook)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_6.addWidget(self.label_6, 0, 0, 1, 2)
        self.pushButtonAddAddressBook = QtGui.QPushButton(self.addressbook)
        self.pushButtonAddAddressBook.setObjectName(_fromUtf8("pushButtonAddAddressBook"))
        self.gridLayout_6.addWidget(self.pushButtonAddAddressBook, 1, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(689, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 1, 1, 1, 1)
        self.tableWidgetAddressBook = QtGui.QTableWidget(self.addressbook)
        self.tableWidgetAddressBook.setAlternatingRowColors(True)
        self.tableWidgetAddressBook.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tableWidgetAddressBook.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidgetAddressBook.setObjectName(_fromUtf8("tableWidgetAddressBook"))
        self.tableWidgetAddressBook.setColumnCount(2)
        self.tableWidgetAddressBook.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetAddressBook.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetAddressBook.setHorizontalHeaderItem(1, item)
        self.tableWidgetAddressBook.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetAddressBook.horizontalHeader().setDefaultSectionSize(400)
        self.tableWidgetAddressBook.horizontalHeader().setHighlightSections(False)
        self.tableWidgetAddressBook.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetAddressBook.verticalHeader().setVisible(False)
        self.gridLayout_6.addWidget(self.tableWidgetAddressBook, 2, 0, 1, 2)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/addressbook.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.addressbook, icon6, _fromUtf8(""))
        self.blackwhitelist = QtGui.QWidget()
        self.blackwhitelist.setObjectName(_fromUtf8("blackwhitelist"))
        self.gridLayout_7 = QtGui.QGridLayout(self.blackwhitelist)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.radioButtonBlacklist = QtGui.QRadioButton(self.blackwhitelist)
        self.radioButtonBlacklist.setChecked(True)
        self.radioButtonBlacklist.setObjectName(_fromUtf8("radioButtonBlacklist"))
        self.gridLayout_7.addWidget(self.radioButtonBlacklist, 0, 0, 1, 2)
        self.radioButtonWhitelist = QtGui.QRadioButton(self.blackwhitelist)
        self.radioButtonWhitelist.setObjectName(_fromUtf8("radioButtonWhitelist"))
        self.gridLayout_7.addWidget(self.radioButtonWhitelist, 1, 0, 1, 2)
        self.pushButtonAddBlacklist = QtGui.QPushButton(self.blackwhitelist)
        self.pushButtonAddBlacklist.setObjectName(_fromUtf8("pushButtonAddBlacklist"))
        self.gridLayout_7.addWidget(self.pushButtonAddBlacklist, 2, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(689, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem5, 2, 1, 1, 1)
        self.tableWidgetBlacklist = QtGui.QTableWidget(self.blackwhitelist)
        self.tableWidgetBlacklist.setAlternatingRowColors(True)
        self.tableWidgetBlacklist.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidgetBlacklist.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidgetBlacklist.setObjectName(_fromUtf8("tableWidgetBlacklist"))
        self.tableWidgetBlacklist.setColumnCount(2)
        self.tableWidgetBlacklist.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetBlacklist.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetBlacklist.setHorizontalHeaderItem(1, item)
        self.tableWidgetBlacklist.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetBlacklist.horizontalHeader().setDefaultSectionSize(400)
        self.tableWidgetBlacklist.horizontalHeader().setHighlightSections(False)
        self.tableWidgetBlacklist.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetBlacklist.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetBlacklist.verticalHeader().setVisible(False)
        self.gridLayout_7.addWidget(self.tableWidgetBlacklist, 3, 0, 1, 2)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/blacklist.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.blackwhitelist, icon7, _fromUtf8(""))
        self.networkstatus = QtGui.QWidget()
        self.networkstatus.setObjectName(_fromUtf8("networkstatus"))
        self.pushButtonStatusIcon = QtGui.QPushButton(self.networkstatus)
        self.pushButtonStatusIcon.setGeometry(QtCore.QRect(680, 440, 21, 23))
        self.pushButtonStatusIcon.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/redicon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonStatusIcon.setIcon(icon8)
        self.pushButtonStatusIcon.setFlat(True)
        self.pushButtonStatusIcon.setObjectName(_fromUtf8("pushButtonStatusIcon"))
        self.tableWidgetConnectionCount = QtGui.QTableWidget(self.networkstatus)
        self.tableWidgetConnectionCount.setGeometry(QtCore.QRect(20, 70, 241, 241))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.tableWidgetConnectionCount.setPalette(palette)
        self.tableWidgetConnectionCount.setFrameShape(QtGui.QFrame.Box)
        self.tableWidgetConnectionCount.setFrameShadow(QtGui.QFrame.Plain)
        self.tableWidgetConnectionCount.setProperty("showDropIndicator", False)
        self.tableWidgetConnectionCount.setAlternatingRowColors(True)
        self.tableWidgetConnectionCount.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tableWidgetConnectionCount.setObjectName(_fromUtf8("tableWidgetConnectionCount"))
        self.tableWidgetConnectionCount.setColumnCount(2)
        self.tableWidgetConnectionCount.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetConnectionCount.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetConnectionCount.setHorizontalHeaderItem(1, item)
        self.tableWidgetConnectionCount.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetConnectionCount.horizontalHeader().setHighlightSections(False)
        self.tableWidgetConnectionCount.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetConnectionCount.verticalHeader().setVisible(False)
        self.labelTotalConnections = QtGui.QLabel(self.networkstatus)
        self.labelTotalConnections.setGeometry(QtCore.QRect(20, 30, 401, 16))
        self.labelTotalConnections.setObjectName(_fromUtf8("labelTotalConnections"))
        self.labelStartupTime = QtGui.QLabel(self.networkstatus)
        self.labelStartupTime.setGeometry(QtCore.QRect(320, 110, 331, 20))
        self.labelStartupTime.setObjectName(_fromUtf8("labelStartupTime"))
        self.labelMessageCount = QtGui.QLabel(self.networkstatus)
        self.labelMessageCount.setGeometry(QtCore.QRect(350, 130, 361, 16))
        self.labelMessageCount.setObjectName(_fromUtf8("labelMessageCount"))
        self.labelPubkeyCount = QtGui.QLabel(self.networkstatus)
        self.labelPubkeyCount.setGeometry(QtCore.QRect(350, 170, 331, 16))
        self.labelPubkeyCount.setObjectName(_fromUtf8("labelPubkeyCount"))
        self.labelBroadcastCount = QtGui.QLabel(self.networkstatus)
        self.labelBroadcastCount.setGeometry(QtCore.QRect(350, 150, 351, 16))
        self.labelBroadcastCount.setObjectName(_fromUtf8("labelBroadcastCount"))
        self.labelLookupsPerSecond = QtGui.QLabel(self.networkstatus)
        self.labelLookupsPerSecond.setGeometry(QtCore.QRect(320, 210, 291, 16))
        self.labelLookupsPerSecond.setObjectName(_fromUtf8("labelLookupsPerSecond"))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/networkstatus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.networkstatus, icon9, _fromUtf8(""))
        self.tabWidget_2.addTab(self.Advenced_messaging, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 885, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setMaximumSize(QtCore.QSize(16777215, 22))
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport_keys = QtGui.QAction(MainWindow)
        self.actionImport_keys.setObjectName(_fromUtf8("actionImport_keys"))
        self.actionManageKeys = QtGui.QAction(MainWindow)
        self.actionManageKeys.setCheckable(False)
        self.actionManageKeys.setEnabled(True)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("dialog-password"))
        self.actionManageKeys.setIcon(icon)
        self.actionManageKeys.setObjectName(_fromUtf8("actionManageKeys"))
        self.actionExit = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("application-exit"))
        self.actionExit.setIcon(icon)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionHelp = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("help-contents"))
        self.actionHelp.setIcon(icon)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionAbout = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("help-about"))
        self.actionAbout.setIcon(icon)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionSettings = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-properties"))
        self.actionSettings.setIcon(icon)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionRegenerateDeterministicAddresses = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("view-refresh"))
        self.actionRegenerateDeterministicAddresses.setIcon(icon)
        self.actionRegenerateDeterministicAddresses.setObjectName(_fromUtf8("actionRegenerateDeterministicAddresses"))
        self.actionDeleteAllTrashedMessages = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("user-trash"))
        self.actionDeleteAllTrashedMessages.setIcon(icon)
        self.actionDeleteAllTrashedMessages.setObjectName(_fromUtf8("actionDeleteAllTrashedMessages"))
        self.actionJoinChan = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("contact-new"))
        self.actionJoinChan.setIcon(icon)
        self.actionJoinChan.setObjectName(_fromUtf8("actionJoinChan"))
        self.menuFile.addAction(self.actionManageKeys)
        self.menuFile.addAction(self.actionDeleteAllTrashedMessages)
        self.menuFile.addAction(self.actionRegenerateDeterministicAddresses)
        self.menuFile.addAction(self.actionJoinChan)
        self.menuFile.addAction(self.actionExit)
        self.menuSettings.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(2)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "BitXBay", None))
        self.label_7.setText(_translate("MainWindow", "Wallet", None))
        self.sync_label.setText(_translate("MainWindow", "(out of sync)", None))
        self.label_8.setText(_translate("MainWindow", "Balance:", None))
        self.label_balance.setText(_translate("MainWindow", "0", None))
        self.label_9.setText(_translate("MainWindow", "Unconfirmed:", None))
        self.label_ucbalance.setText(_translate("MainWindow", "0", None))
        self.label_45.setText(_translate("MainWindow", "Pay to:", None))
        self.label_46.setText(_translate("MainWindow", "Label:", None))
        self.label_47.setText(_translate("MainWindow", "Amount:", None))
        self.sendbtc.setText(_translate("MainWindow", "Send", None))
        self.label_44.setText(_translate("MainWindow", "Send", None))
        self.bitcoinaddresses.setSortingEnabled(True)
        item = self.bitcoinaddresses.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Label", None))
        item = self.bitcoinaddresses.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Address", None))
        item = self.bitcoinaddresses.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Amount", None))
        self.label_48.setText(_translate("MainWindow", "My addresses", None))
        self.label_49.setText(_translate("MainWindow", "Transactions", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Address", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Category", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Amount", None))
        self.label_10.setText(_translate("MainWindow", "For full bitcoin functions you can use bitcoin-qt that is now running", None))
        self.label_11.setText(_translate("MainWindow", "Amount must be >0", None))
        self.pushButton.setText(_translate("MainWindow", "New btc address", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "Wallet", None))
        self.label_24.setText(_translate("MainWindow", "Auto deal:", None))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "BitXBay escrow address of merchant", None))
        self.pushButtonManualEscrowBuyer.setText(_translate("MainWindow", "Start deal", None))
        self.label_28.setText(_translate("MainWindow", "Auto escrow deals that not finished:", None))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.escrowlabelforbuyer.setPlaceholderText(_translate("MainWindow", "Label for escrow deal(recommend)", None))
        self.frombox.setItemText(0, _translate("MainWindow", "Select bitmessage sender\'s address", None))
        self.pushButton_2.setText(_translate("MainWindow", " New address", None))
        self.comment.setPlainText(_translate("MainWindow", "Comment for merchant. Type here the shipping address or other important information.", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.buyer), _translate("MainWindow", "Buyer", None))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.label_40.setText(_translate("MainWindow", "Auto escrow deals that not finished:", None))
        self.newmerchantaddress.setText(_translate("MainWindow", " New merchant escrow address", None))
        self.youids.setSortingEnabled(True)
        item = self.youids.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Address", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.merchant), _translate("MainWindow", "Merchant", None))
        self.label_20.setText(_translate("MainWindow", "Escrow is a deal type in which the money is stuck between the seller and the buyer. BitXBay escrow is a deal between two parties without intermediaries. Intermediaries replaced by 5% insurence payments from buyer and seller to multisig addresses. Both parties can get back insurent payments only when the deal completed successfully or canceled by both parties as well by both parties. The process takes place without the use of a third party, using multisig bitcoin addresses. These addresses are created with the public keys of both parties.\n"
" ", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab6), _translate("MainWindow", "Escrow", None))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.pushButton_3.setText(_translate("MainWindow", "Sell", None))
        self.offertype.setItemText(0, _translate("MainWindow", "Goods", None))
        self.offertype.setItemText(1, _translate("MainWindow", "Services", None))
        self.offertype.setItemText(2, _translate("MainWindow", "Currency exchange", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Categories(don\'t work yet)", None))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Search...(don\'t work yet)", None))
        self.label_12.setText(_translate("MainWindow", "Be careful when buying a reversible currency like Paypal. Confirm the transaction only when verification period has passed. For PayPal it may be 2 months.", None))
        self.pushButton_4.setText(_translate("MainWindow", "Search", None))
        self.location.setItemText(0, _translate("MainWindow", "Location(don\'t work yet)", None))
        self.pushButton_5.setText(_translate("MainWindow", "Refresh", None))
        self.checkBox.setText(_translate("MainWindow", "Auto refresh every hour", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab7), _translate("MainWindow", "Decentralized trade", None))
        self.inboxSearchLineEdit.setPlaceholderText(_translate("MainWindow", "Search", None))
        self.inboxSearchOptionCB.setItemText(0, _translate("MainWindow", "All", None))
        self.inboxSearchOptionCB.setItemText(1, _translate("MainWindow", "To", None))
        self.inboxSearchOptionCB.setItemText(2, _translate("MainWindow", "From", None))
        self.inboxSearchOptionCB.setItemText(3, _translate("MainWindow", "Subject", None))
        self.inboxSearchOptionCB.setItemText(4, _translate("MainWindow", "Message", None))
        self.tableWidgetInbox.setSortingEnabled(True)
        item = self.tableWidgetInbox.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "To", None))
        item = self.tableWidgetInbox.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "From", None))
        item = self.tableWidgetInbox.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Subject", None))
        item = self.tableWidgetInbox.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Received", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.inbox), _translate("MainWindow", "Inbox", None))
        self.pushButtonLoadFromAddressBook.setText(_translate("MainWindow", "Load from Address book", None))
        self.pushButtonFetchNamecoinID.setText(_translate("MainWindow", "Fetch Namecoin ID", None))
        self.label_4.setText(_translate("MainWindow", "Message:", None))
        self.label_3.setText(_translate("MainWindow", "Subject:", None))
        self.radioButtonSpecific.setText(_translate("MainWindow", "Send to one or more specific people", None))
        self.textEditMessage.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p></body></html>", None))
        self.label.setText(_translate("MainWindow", "To:", None))
        self.label_2.setText(_translate("MainWindow", "From:", None))
        self.radioButtonBroadcast.setText(_translate("MainWindow", "Broadcast to everyone who is subscribed to your address", None))
        self.pushButtonSend.setText(_translate("MainWindow", "Send", None))
        self.labelSendBroadcastWarning.setText(_translate("MainWindow", "Be aware that broadcasts are only encrypted with your address. Anyone who knows your address can read them.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.send), _translate("MainWindow", "Send", None))
        self.sentSearchLineEdit.setPlaceholderText(_translate("MainWindow", "Search", None))
        self.sentSearchOptionCB.setItemText(0, _translate("MainWindow", "All", None))
        self.sentSearchOptionCB.setItemText(1, _translate("MainWindow", "To", None))
        self.sentSearchOptionCB.setItemText(2, _translate("MainWindow", "From", None))
        self.sentSearchOptionCB.setItemText(3, _translate("MainWindow", "Subject", None))
        self.sentSearchOptionCB.setItemText(4, _translate("MainWindow", "Message", None))
        self.tableWidgetSent.setSortingEnabled(True)
        item = self.tableWidgetSent.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "To", None))
        item = self.tableWidgetSent.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "From", None))
        item = self.tableWidgetSent.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Subject", None))
        item = self.tableWidgetSent.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Status", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sent), _translate("MainWindow", "Sent", None))
        self.pushButtonNewAddress.setText(_translate("MainWindow", "New", None))
        self.tableWidgetYourIdentities.setSortingEnabled(True)
        item = self.tableWidgetYourIdentities.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Label (not shown to anyone)", None))
        item = self.tableWidgetYourIdentities.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Address", None))
        item = self.tableWidgetYourIdentities.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Stream", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.youridentities), _translate("MainWindow", "Your Identities", None))
        self.label_5.setText(_translate("MainWindow", "Here you can subscribe to \'broadcast messages\' that are sent by other users. Messages will appear in your Inbox. Addresses here override those on the Blacklist tab.", None))
        self.pushButtonAddSubscription.setText(_translate("MainWindow", "Add new Subscription", None))
        self.tableWidgetSubscriptions.setSortingEnabled(True)
        item = self.tableWidgetSubscriptions.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Label", None))
        item = self.tableWidgetSubscriptions.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Address", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.subscriptions), _translate("MainWindow", "Subscriptions", None))
        self.label_6.setText(_translate("MainWindow", "The Address book is useful for adding names or labels to other people\'s Bitmessage addresses so that you can recognize them more easily in your inbox. You can add entries here using the \'Add\' button, or from your inbox by right-clicking on a message.", None))
        self.pushButtonAddAddressBook.setText(_translate("MainWindow", "Add new entry", None))
        self.tableWidgetAddressBook.setSortingEnabled(True)
        item = self.tableWidgetAddressBook.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name or Label", None))
        item = self.tableWidgetAddressBook.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Address", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.addressbook), _translate("MainWindow", "Address Book", None))
        self.radioButtonBlacklist.setText(_translate("MainWindow", "Use a Blacklist (Allow all incoming messages except those on the Blacklist)", None))
        self.radioButtonWhitelist.setText(_translate("MainWindow", "Use a Whitelist (Block all incoming messages except those on the Whitelist)", None))
        self.pushButtonAddBlacklist.setText(_translate("MainWindow", "Add new entry", None))
        self.tableWidgetBlacklist.setSortingEnabled(True)
        item = self.tableWidgetBlacklist.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name or Label", None))
        item = self.tableWidgetBlacklist.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Address", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.blackwhitelist), _translate("MainWindow", "Blacklist", None))
        item = self.tableWidgetConnectionCount.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Stream #", None))
        item = self.tableWidgetConnectionCount.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Connections", None))
        self.labelTotalConnections.setText(_translate("MainWindow", "Total connections: 0", None))
        self.labelStartupTime.setText(_translate("MainWindow", "Since startup at asdf:", None))
        self.labelMessageCount.setText(_translate("MainWindow", "Processed 0 person-to-person message.", None))
        self.labelPubkeyCount.setText(_translate("MainWindow", "Processed 0 public key.", None))
        self.labelBroadcastCount.setText(_translate("MainWindow", "Processed 0 broadcast.", None))
        self.labelLookupsPerSecond.setText(_translate("MainWindow", "Inventory lookups per second: 0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.networkstatus), _translate("MainWindow", "Network Status", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.Advenced_messaging), _translate("MainWindow", "Advanced messaging", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionImport_keys.setText(_translate("MainWindow", "Import keys", None))
        self.actionManageKeys.setText(_translate("MainWindow", "Manage keys", None))
        self.actionExit.setText(_translate("MainWindow", "Quit", None))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionHelp.setText(_translate("MainWindow", "Help", None))
        self.actionHelp.setShortcut(_translate("MainWindow", "F1", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionSettings.setText(_translate("MainWindow", "Settings", None))
        self.actionRegenerateDeterministicAddresses.setText(_translate("MainWindow", "Regenerate deterministic addresses", None))
        self.actionDeleteAllTrashedMessages.setText(_translate("MainWindow", "Delete all trashed messages", None))
        self.actionJoinChan.setText(_translate("MainWindow", "Join / Create chan", None))

import bitmessage_icons_rc
