#!/usr/bin/env python

import sys
from electrum import NetworkProxy, print_json



try:
    address = sys.argv[1]
except Exception:
    print "usage: get_balance <bitcoin_address>"
    sys.exit(1)


network = NetworkProxy()
network.start(start_daemon=True)
result = network.synchronous_get([('blockchain.address.get_balance',[address])])[0]
print_json(result)


